### ISSUE TITLE
Logout functionality

### ISSUE THREAD

**Issue by gemaSantiago** [canoo/dolphin-platform#40] opened 2016-01-25 13:39 UTC
One has to be able to logout from the server, e.g. by calling clientContext.disconnect();

**Comment by hendrikebbers** [comment] 2016-01-25 20:13
@aalmiray @netopyr Can we close this issue? We have a disconnect method and in the new version the push is deactivated after disconnect. In 0.8 all controllers will be removed automatically when calling disconnect on the client

**Comment by aalmiray** [comment] 2016-01-25 20:24
Here's a list of things I think we must validate before closing this issue for good (or create additional issues for missing items if you think it's better for granularity)

When client disconnects from the server gracefully (by invoking `clientContext.disconnect()`:
- all server side resources related to this client session, allocated by DP, will be de-allocated/freed; this includes controllers, beans and DP plumbing. 
- DP must invoke methods annotated with `@PostConstruct` on all existing controllers and managed instances.
- DP must ensure that the HTTP session becomes invalidated.
- client DP stops any background updates (such as long polling).
- client DP shutdowns all resources allocated by it. This includes OpenDolphin internals.

**Comment by hendrikebbers** [comment] 2016-01-25 21:30
I don't think that a `clientContext.disconnect()` should invalidate the session. The session can contain much more than the dolphin objects. I think a disconnect should:
- stop long polling
- call `@PostConstruct` on all controller instances
- remove all dolphin resources from the session

The first 2 points will be resolved with 0.8
The 3rd point is related to https://github.com/canoo/dolphin-platform/issues/50

**Comment by hendrikebbers** [comment] 2016-03-18 15:50
resolved in #131

**Comment by hendrikebbers** [comment] 2016-06-03 11:33
New functionality is merged in master and will be available with release 0.8.7. Since this error happens in an application that is based on DP we can not test it directly. Therefore I will move this issue to milestone 0.8.7 and we can check if the issue is fixed once the application is based on 0.8.6.

**Comment by hendrikebbers** [comment] 2016-07-14 09:28
Maybe related to #210 and #221

**Closed** 2017-10-10 08:08 UTC
Labels: Component: Java Client, Component: JavaScript Client, Type: Feature
