### ISSUE TITLE
java clients: no notification about connection problems after connection loss and reconnect

### ISSUE THREAD

**Issue by blackdrag** [canoo/dolphin-platform#423] opened 2017-03-23 10:16 UTC
Symptoms:
Assume you are connected by the java client to your server and the connection is disturbed, causing your client not able to connect to the server for at least 3 minutes. You will not have any exception or notification about a problem with your connection in the client. But if you reconnect after that time all communication with the server ends in nothing. No bean updates, no execution of dolphin actions. I tested this by disconnecting my wlan connection for a bout 3 minutes. I noticed, that if it is less than 2 minutes there is no problem. I noticed a longpoll going on, but not ending till the connection is back. So it is a much longer longpoll than the usual 5s. 

Expected behavior:
either to be able to reconnect to the server and continue working as if nothing happened, or a controllable way of DP telling me about a loss of connection to the server. Then we can tell the user and maybe go back to the login screen or otherwise reset the UI.

**Comment by timo0** [comment] 2017-03-27 15:35
Are there any news here?

**Comment by hendrikebbers** [comment] 2017-04-07 13:51
Duplicate of https://github.com/canoo/dolphin-platform/issues/303

**Closed by hendrikebbers** 2017-04-07 13:51 UTC
Labels: Component: Java Client, Customer-Issue, Type: Bug
