### ISSUE TITLE
spring wiring missing for DolphinSessionListener

### ISSUE THREAD

**Issue by blackdrag** [canoo/dolphin-platform#456] opened 2017-04-13 08:01 UTC
> com.canoo.dolphin.server.context.DolphinContextException: Error while handling onSessionCreated listener
	at com.canoo.dolphin.server.context.DolphinSessionLifecycleHandler.onSessionCreated(DolphinSessionLifecycleHandler.java:56)
	at com.canoo.dolphin.server.context.DolphinContextFilter.doFilter(DolphinContextFilter.java:75)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239)
...
Caused by: org.springframework.beans.factory.NoSuchBeanDefinitionException: No qualifying bean of type [com.canoo.icos.casemanager.server.configuration.CaseManagerSessionListener] is defined
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.getBean(DefaultListableBeanFactory.java:371)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.getBean(DefaultListableBeanFactory.java:331)
	at org.springframework.context.support.AbstractApplicationContext.getBean(AbstractApplicationContext.java:968)
	at com.canoo.dolphin.server.spring.AbstractSpringContainerManager.createListener(AbstractSpringContainerManager.java:52)
	at com.canoo.dolphin.server.bootstrap.DolphinPlatformBootstrap$3.call(DolphinPlatformBootstrap.java:166)
	at com.canoo.dolphin.server.bootstrap.DolphinPlatformBootstrap$3.call(DolphinPlatformBootstrap.java:163)
	at com.canoo.dolphin.server.context.DolphinSessionLifecycleHandler.onSessionCreated(DolphinSessionLifecycleHandler.java:54)
	... 71 more

This happened when trying to use The DolphinSessionListener

**Comment by hendrikebbers** [comment] 2017-04-13 08:23
https://github.com/canoo/dolphin-platform/pull/455

**Comment by hendrikebbers** [comment] 2017-04-13 09:45
Duplicate of https://github.com/canoo/dolphin-platform/issues/354

**Closed** 2017-04-13 09:47 UTC
Labels: Customer-Issue, Type: Bug
