### ISSUE TITLE
saving data to database

### ISSUE THREAD

**Issue by mostfa-ayad** [canoo/dolphin-platform#350] opened 2017-02-05 20:12 UTC
can you give me a short example for using spring data with dolphin 
with best best practice  
not atutorial just example and i will try to read

**Comment by mostfa-ayad** [comment] 2017-02-06 22:08
whats the meaning of this msg
2017-02-07 00:06:41.342  INFO 7460 --- [io-8080-exec-10] o.o.c.s.a.CreatePresentationModelAction  : Ignoring create PM 'com.test.model.BaseM' since it is already in the model store.

**Comment by timo0** [comment] 2017-03-20 10:48
Hi, will close this Issue as duplicate of #404

**Closed by timo0** 2017-03-20 10:48 UTC
Labels: Community-Issue
