### ISSUE TITLE
Allow ObservableList to be sorted server side

### ISSUE THREAD

**Issue by aalmiray** [canoo/dolphin-platform#16] opened 2016-01-22 10:37 UTC
Sorting an `ObservableList` on the server side does not notify clients of changes

**Comment by netopyr** [comment] 2016-01-26 13:51
How is ObservableList sorted?

**Comment by aalmiray** [comment] 2016-01-26 14:09
`ObservableList` (JavaFX)  can be sorted by wrapping in with `SortedList`. The problem here is that sorting may be part of business logic, as such, it's an operation that must be performed on the server side. Currently DP's `ObservableList` does not reflect any changes when sorted, for example using

    Collections.sort(dpObservableList)

or even (Java8)

    dpObservableList.sort()

It's worth mentioning that OD's PMs and attributes do not expose order information in any way AFAIK

**Comment by netopyr** [comment] 2016-01-26 15:49
https://github.com/canoo/dolphin-platform/issues/29

**Comment by netopyr** [comment] 2016-01-26 15:53
List.sort() uses the listIterator() for modifying the list, which we have not implemented yet. Closing this issue as it is a duplicate of #29.

**Closed by netopyr** 2016-01-26 15:53 UTC
Labels: Component: Core, Type: Bug

**Comment by aalmiray** [comment] 2016-01-26 16:48
Can't say it's a duplicate. Implementing listIterator is not enough. DP must transfer order information too. Sorting an ObservableList does not add/remove elements. AFAIK DP does not track element indexes, so how could it tell the other side elements have been rearranged?

**Comment by netopyr** [comment] 2016-01-26 20:58
DP does track element indexes.
